apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: myapp
    name: myapp-rs

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  
  template:
    metadata:
      labels:
        app: myapp

    spec:
      containers:
        - name: nginx-cont
          image: nginx
